# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 00dd318997b84e2eac8a0cc6d48d82861e9d7f06ecb6a86dd56688e5793f1ac92472dc0cbe371f7d42eb9db3ad38033f259a32315069962eba7371f95bf1ae13

test:
  secret_key_base: b30f275682bca32679d7bf00a483d1267a10c8c812bd9301634ba0c5d489a422f89f9e97235949dbe2bb2311a874189ba026f9c1dcf603bbf97623519b615bd4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
